name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0
        with:
          chrome-version: stable

      - name: Set Chrome in PATH on Linux
        if: runner.os == 'Linux'
        run: echo "/opt/hostedtoolcache/chromium/stable/x64" >> $GITHUB_PATH

      - name: Set Chrome in PATH on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $chromePath = "C:\tools\chrome"
          echo "$chromePath" >> $Env:GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4

      - name: Setup local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        name: Cache the virtual environment
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install project dependencies
        run: poetry install --with dev --no-root

      - name: Run example test
        run: poetry run pytest tests/test_example.py

      - name: Upload workflow screenshots on Linux
        if: runner.os == 'Linux' && always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.python-version }}-${{ github.run_id }}
          path: /tmp/screenshots/*

      - name: Upload workflow screenshots on Windows
        if: runner.os == 'Windows' && always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.python-version }}-${{ github.run_id }}
          path: C:\temp\screenshots\*

      - name: Run multiprocess test
        run: poetry run pytest tests/test_multiprocess.py
